import {
    GET_DEPARTURE_INIT,
    GET_DEPARTURE_SUCCCESS,
    GET_DEPARTURE_FAILURE,
    DELETE_DEPARTURE_INIT,
    DELETE_DEPARTURE_SUCCCESS,
    DELETE_DEPARTURE_FAILURE,
    CREATE_DEPARTURE_INIT,
    CREATE_DEPARTURE_SUCCCESS,
    CREATE_DEPARTURE_FAILURE,
    USER_UPDATE_INIT,
    USER_UPDATE_SUCCESS,
    USER_UPDATE_FAILURE,
    USER_GET_INIT,
    USER_GET_SUCCESS,
    USER_GET_FAILURE,} from "./constants"

